project:
  type: website

website:
  sidebar:
    background: "#355464"
    foreground: "#99D9D9"
    search: true
    title: "DSAN-5000 Project - Public Transit Analysis"
    subtitle: "text"
    contents:
      - text: "Name: Josh Sweren"
      - text: "GU Net ID: jms819"
      - text: "---------"
      - href: https://www.linkedin.com/in/joshua-sweren-26599a15b/
        text: LinkedIn
      - text: "----------"
      - href: index.ipynb
        text: About Me
      - href: code/code.ipynb
        text: Code
      - href: data/data.ipynb
        text: Data
      - href: introduction/introduction.ipynb
        text: Introduction
      - href: gathering/gathering.ipynb
        text: Data Gathering
      - href: cleaning/cleaning.ipynb
        text: Data Cleaning
      - href: eda/eda.ipynb
        text: Data Exploration
      - href: naive_bayes/naive_bayes.ipynb
        text: Naive Bayes
      - href: clustering/clustering.ipynb
        text: Clustering
      - href: dimensionality_reduction/dimensionality_reduction.ipynb
        text: Dimensionality Reduction
      - section: "Decision Trees"
        contents:
        - href: decision_trees/regression/regression.ipynb
          text: Regression
        - href: decision_trees/classification/classification.ipynb
          text: Classification
      - href: conclusions/conclusions.ipynb
        text: Conclusions
format:
  html:
    theme: 
      - united
      - styles.scss
    toc: true



